# Generated by Django 4.2.1 on 2023-05-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='image_number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Номер картинки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place'),
        ),
    ]
