# Generated by Django 4.2.1 on 2023-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placeimage_image_number_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['id'], 'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['place'], 'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image_number',
            field=models.IntegerField(default=0, verbose_name='Номер картинки'),
        ),
    ]
